export default {
  logIn:"/login",
  register:"/register",
  resetPassword:"/reset-password",
  index:"/",
  account:"/account",
  deposit:"/deposit",
  withdrawal:"/withdrawal",
  cardManage:"/card-manage",
  personalInfoWrite:"/personal-info-write",
  personalInfoChecked:"/personal-info-checked",
  changePassword:"/change-password",
  tradingOrder:"/trading-order",
  depositAndWithdrawalReport:"/deposit-and-withdrawal-report",
  customerList:"/customer-list",
  customerTradingOrder:"/customer-trading-order",
  customerDepositAndWithdrawalReport:"/customer-deposit-and-withdrawal-report",
  paymentCallback:"/payment-callback/:checkoutId/:chargeId",
  decorator:"/decorator",
  demoDetails:"/system/demo/details/:action/:id?",
  demo:"/system/demo",
  system:"/system",
  ReactRangePicker:"/react-range-picker",
 };
    